server:
  port: 7084
  ssl:
    enabled: false

com:
  c4-soft:
    springaddons:
      oidc:
        ops:
        - iss: https://localhost:8443/realms/master
          authorities:
          - path: $.realm_access.roles
          username-claim: preferred_username
        resourceserver:
          permit-all:
          - /users/me
          - /actuator/health/readiness
          - /actuator/health/liveness

logging:
  level:
    org:
      springframework:
        security: DEBUG
        
---
server:
  ssl:
    enabled: true

spring:
  config:
    activate:
      on-profile: ssl